-- MySQL Script generated by MySQL Workbench
-- Mon Nov 21 00:40:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`base_setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_setor` (
  `id_setor` INT NOT NULL,
  `setor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_setor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_origem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_origem` (
  `id_origem` INT NOT NULL,
  `origem` VARCHAR(45) NULL,
  PRIMARY KEY (`id_origem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_pais` (
  `id_pais` INT NOT NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_estado` (
  `id_estado` INT NOT NULL,
  `uf` CHAR(2) NULL,
  `estado` VARCHAR(45) NULL,
  `id_pais` INT NULL,
  `base_pais_id_pais` INT NOT NULL,
  PRIMARY KEY (`id_estado`),
  INDEX `fk_base_estado_base_pais1_idx` (`base_pais_id_pais` ASC) VISIBLE,
  CONSTRAINT `fk_base_estado_base_pais1`
    FOREIGN KEY (`base_pais_id_pais`)
    REFERENCES `mydb`.`base_pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_empresas` (
  `id_empresas` INT NOT NULL AUTO_INCREMENT,
  `empresa` VARCHAR(50) NOT NULL,
  `porte` VARCHAR(45) NULL,
  `capital` VARCHAR(45) NULL,
  `receita` FLOAT NULL,
  `controle` VARCHAR(45) NULL,
  `hist_emp` VARCHAR(200) NULL,
  `perfil_emp` VARCHAR(45) NULL,
  `parceiros` TINYINT NULL,
  `concorrentes` TINYINT NULL,
  `clientes` VARCHAR(45) NULL,
  `fornecedores` TINYINT NULL,
  `url_proposta` VARCHAR(200) NULL,
  `id_setor` INT NULL,
  `id_origem` INT NULL,
  `id_estado` INT NULL,
  `id_pais` INT NULL,
  PRIMARY KEY (`id_empresas`),
  INDEX `id_setor_idx` (`id_setor` ASC) VISIBLE,
  INDEX `id_origem_idx` (`id_origem` ASC) VISIBLE,
  INDEX `id_pais_idx` (`id_pais` ASC) VISIBLE,
  INDEX `id_estado_idx` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `id_setor`
    FOREIGN KEY (`id_setor`)
    REFERENCES `mydb`.`base_setor` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_origem`
    FOREIGN KEY (`id_origem`)
    REFERENCES `mydb`.`base_origem` (`id_origem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `mydb`.`base_estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pais`
    FOREIGN KEY (`id_pais`)
    REFERENCES `mydb`.`base_pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_cidade` (
  `id_cidade` INT NOT NULL,
  `cidade` VARCHAR(45) NULL,
  `id_estado` INT NULL,
  `base_estado_id_estado` INT NOT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_base_cidade_base_estado1_idx` (`base_estado_id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_base_cidade_base_estado1`
    FOREIGN KEY (`base_estado_id_estado`)
    REFERENCES `mydb`.`base_estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_endereco` (
  `id_endereco` INT NOT NULL,
  `bairro` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `id_cidade` INT NULL,
  `base_cidade_id_cidade` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_base_endereco_base_cidade1_idx` (`base_cidade_id_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_base_endereco_base_cidade1`
    FOREIGN KEY (`base_cidade_id_cidade`)
    REFERENCES `mydb`.`base_cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_esp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_esp` (
  `id_esp` INT NOT NULL,
  `especificacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_esp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_area` (
  `id_area` INT NOT NULL,
  `area` VARCHAR(45) NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_cargo` (
  `id_cargo` INT NOT NULL,
  `cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_servicos` (
  `id_servicos` INT NOT NULL,
  `servico` VARCHAR(45) NULL,
  `id_lds` INT NULL,
  PRIMARY KEY (`id_servicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_clientes` (
  `id_clientes` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `contato_chave` TINYINT NULL,
  `telefone` CHAR(12) NULL,
  `celular` CHAR(12) NULL,
  `email` VARCHAR(45) NULL,
  `linkedin` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `est_conv` VARCHAR(45) NULL,
  `obs_cliente` VARCHAR(300) NULL,
  `id_esp` INT NULL,
  `id_area` VARCHAR(45) NULL,
  `id_empresa` VARCHAR(45) NULL,
  `id_cargo` VARCHAR(45) NULL,
  `id_cidade` VARCHAR(45) NULL,
  `id_servicos` INT NULL,
  `base_endereco_id_endereco` INT NOT NULL,
  `base_cidade_id_cidade` INT NOT NULL,
  `base_esp_id_esp` INT NOT NULL,
  `base_area_id_area` INT NOT NULL,
  `base_cargo_id_cargo` INT NOT NULL,
  `base_servicos_id_servicos` INT NOT NULL,
  PRIMARY KEY (`id_clientes`),
  INDEX `fk_base_clientes_base_endereco1_idx` (`base_endereco_id_endereco` ASC) VISIBLE,
  INDEX `fk_base_clientes_base_cidade1_idx` (`base_cidade_id_cidade` ASC) VISIBLE,
  INDEX `fk_base_clientes_base_esp1_idx` (`base_esp_id_esp` ASC) VISIBLE,
  INDEX `fk_base_clientes_base_area1_idx` (`base_area_id_area` ASC) VISIBLE,
  INDEX `fk_base_clientes_base_cargo1_idx` (`base_cargo_id_cargo` ASC) VISIBLE,
  INDEX `fk_base_clientes_base_servicos1_idx` (`base_servicos_id_servicos` ASC) VISIBLE,
  CONSTRAINT `fk_base_clientes_base_endereco1`
    FOREIGN KEY (`base_endereco_id_endereco`)
    REFERENCES `mydb`.`base_endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_clientes_base_cidade1`
    FOREIGN KEY (`base_cidade_id_cidade`)
    REFERENCES `mydb`.`base_cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_clientes_base_esp1`
    FOREIGN KEY (`base_esp_id_esp`)
    REFERENCES `mydb`.`base_esp` (`id_esp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_clientes_base_area1`
    FOREIGN KEY (`base_area_id_area`)
    REFERENCES `mydb`.`base_area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_clientes_base_cargo1`
    FOREIGN KEY (`base_cargo_id_cargo`)
    REFERENCES `mydb`.`base_cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_clientes_base_servicos1`
    FOREIGN KEY (`base_servicos_id_servicos`)
    REFERENCES `mydb`.`base_servicos` (`id_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_funcionarios` (
  `id_funcionarios` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `cpf` CHAR(11) NULL,
  `rg` CHAR(9) NULL,
  `telefone` CHAR(12) NULL,
  `celular` CHAR(12) NULL,
  `email` VARCHAR(45) NULL,
  `linkedin` VARCHAR(45) NULL,
  `ident` VARCHAR(45) NULL,
  `dt_aniv` DATE NULL,
  `est_civil` VARCHAR(45) NULL,
  `id_endereco` INT NULL,
  `id_esp` INT NULL,
  `id_estado` INT NULL,
  `id_cargo` INT NULL,
  `id_cidade` INT NULL,
  `id_area` INT NULL,
  `base_cidade_id_cidade` INT NOT NULL,
  `base_cargo_id_cargo` INT NOT NULL,
  `base_area_id_area` INT NOT NULL,
  `base_esp_id_esp` INT NOT NULL,
  `base_endereco_id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_funcionarios`),
  INDEX `fk_base_funcionarios_base_cidade1_idx` (`base_cidade_id_cidade` ASC) VISIBLE,
  INDEX `fk_base_funcionarios_base_cargo1_idx` (`base_cargo_id_cargo` ASC) VISIBLE,
  INDEX `fk_base_funcionarios_base_area1_idx` (`base_area_id_area` ASC) VISIBLE,
  INDEX `fk_base_funcionarios_base_esp1_idx` (`base_esp_id_esp` ASC) VISIBLE,
  INDEX `fk_base_funcionarios_base_endereco1_idx` (`base_endereco_id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_base_funcionarios_base_cidade1`
    FOREIGN KEY (`base_cidade_id_cidade`)
    REFERENCES `mydb`.`base_cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_funcionarios_base_cargo1`
    FOREIGN KEY (`base_cargo_id_cargo`)
    REFERENCES `mydb`.`base_cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_funcionarios_base_area1`
    FOREIGN KEY (`base_area_id_area`)
    REFERENCES `mydb`.`base_area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_funcionarios_base_esp1`
    FOREIGN KEY (`base_esp_id_esp`)
    REFERENCES `mydb`.`base_esp` (`id_esp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_funcionarios_base_endereco1`
    FOREIGN KEY (`base_endereco_id_endereco`)
    REFERENCES `mydb`.`base_endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_comb_situ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_comb_situ` (
  `id_comb_situ` INT NOT NULL,
  `situacao 1` TINYINT NULL,
  `situacao 2` TINYINT NULL,
  `situacao 3` TINYINT NULL,
  `situacao 4` TINYINT NULL,
  `situacao 5` TINYINT NULL,
  `situacao 6` TINYINT NULL,
  `valor_comb_situ` FLOAT NULL,
  `id_pagamentos` INT NULL,
  PRIMARY KEY (`id_comb_situ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_fatores_custos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_fatores_custos` (
  `id_fator` INT NOT NULL,
  `id_comb_situ` INT NULL,
  `base_comb_situ_id_comb_situ` INT NOT NULL,
  PRIMARY KEY (`id_fator`),
  INDEX `fk_base_fatores_custos_base_comb_situ1_idx` (`base_comb_situ_id_comb_situ` ASC) VISIBLE,
  CONSTRAINT `fk_base_fatores_custos_base_comb_situ1`
    FOREIGN KEY (`base_comb_situ_id_comb_situ`)
    REFERENCES `mydb`.`base_comb_situ` (`id_comb_situ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_custos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_custos` (
  `id_custos` INT NOT NULL,
  `custo_eq_int` FLOAT NULL,
  `custo_desloc` FLOAT NULL,
  `custo_outros` FLOAT NULL,
  `id_pagamentos` INT NULL,
  `id_fator` INT NULL,
  `id_projetos` INT NULL,
  `base_fatores_custos_id_fator` INT NOT NULL,
  PRIMARY KEY (`id_custos`),
  INDEX `fk_base_custos_base_fatores_custos1_idx` (`base_fatores_custos_id_fator` ASC) VISIBLE,
  CONSTRAINT `fk_base_custos_base_fatores_custos1`
    FOREIGN KEY (`base_fatores_custos_id_fator`)
    REFERENCES `mydb`.`base_fatores_custos` (`id_fator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_pagamentos` (
  `id_pagamentos` INT NOT NULL,
  `beneficio` VARCHAR(45) NULL,
  `dt_pag` DATE NULL,
  `status_pag` VARCHAR(45) NULL,
  `salario` VARCHAR(45) NULL,
  `id_projetos` INT NULL,
  `id_funcionarios` INT NULL,
  `id_clientes` INT NULL,
  `base_clientes_id_clientes` INT NOT NULL,
  `base_funcionarios_id_funcionarios` INT NOT NULL,
  `base_custos_id_custos` INT NOT NULL,
  `base_comb_situ_id_comb_situ` INT NOT NULL,
  PRIMARY KEY (`id_pagamentos`),
  INDEX `fk_base_pagamentos_base_clientes1_idx` (`base_clientes_id_clientes` ASC) VISIBLE,
  INDEX `fk_base_pagamentos_base_funcionarios1_idx` (`base_funcionarios_id_funcionarios` ASC) VISIBLE,
  INDEX `fk_base_pagamentos_base_custos1_idx` (`base_custos_id_custos` ASC) VISIBLE,
  INDEX `fk_base_pagamentos_base_comb_situ1_idx` (`base_comb_situ_id_comb_situ` ASC) VISIBLE,
  CONSTRAINT `fk_base_pagamentos_base_clientes1`
    FOREIGN KEY (`base_clientes_id_clientes`)
    REFERENCES `mydb`.`base_clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_pagamentos_base_funcionarios1`
    FOREIGN KEY (`base_funcionarios_id_funcionarios`)
    REFERENCES `mydb`.`base_funcionarios` (`id_funcionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_pagamentos_base_custos1`
    FOREIGN KEY (`base_custos_id_custos`)
    REFERENCES `mydb`.`base_custos` (`id_custos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_pagamentos_base_comb_situ1`
    FOREIGN KEY (`base_comb_situ_id_comb_situ`)
    REFERENCES `mydb`.`base_comb_situ` (`id_comb_situ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_comb_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_comb_servicos` (
  `id_servicos` INT NULL,
  `id_clientes` INT NULL,
  `base_clientes_id_clientes` INT NOT NULL,
  `base_servicos_id_servicos` INT NOT NULL,
  INDEX `fk_base_comb_servicos_base_clientes1_idx` (`base_clientes_id_clientes` ASC) VISIBLE,
  INDEX `fk_base_comb_servicos_base_servicos1_idx` (`base_servicos_id_servicos` ASC) VISIBLE,
  CONSTRAINT `fk_base_comb_servicos_base_clientes1`
    FOREIGN KEY (`base_clientes_id_clientes`)
    REFERENCES `mydb`.`base_clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_comb_servicos_base_servicos1`
    FOREIGN KEY (`base_servicos_id_servicos`)
    REFERENCES `mydb`.`base_servicos` (`id_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_lds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_lds` (
  `id_lds` INT NOT NULL,
  `linha_de_servico` VARCHAR(45) NULL,
  `base_servicos_id_servicos` INT NOT NULL,
  PRIMARY KEY (`id_lds`),
  INDEX `fk_base_lds_base_servicos1_idx` (`base_servicos_id_servicos` ASC) VISIBLE,
  CONSTRAINT `fk_base_lds_base_servicos1`
    FOREIGN KEY (`base_servicos_id_servicos`)
    REFERENCES `mydb`.`base_servicos` (`id_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_comb_unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_comb_unidade` (
  `id_comb_unidade` INT NOT NULL,
  `uni_edu` TINYINT NULL,
  `uni_est` TINYINT NULL,
  `uni_sus` TINYINT NULL,
  `uni_com` TINYINT NULL,
  `id_lds` INT NULL,
  `base_lds_id_lds` INT NOT NULL,
  PRIMARY KEY (`id_comb_unidade`),
  INDEX `fk_base_comb_unidade_base_lds1_idx` (`base_lds_id_lds` ASC) VISIBLE,
  CONSTRAINT `fk_base_comb_unidade_base_lds1`
    FOREIGN KEY (`base_lds_id_lds`)
    REFERENCES `mydb`.`base_lds` (`id_lds`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_unidade` (
  `id_unidade` INT NOT NULL,
  `unidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_unidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_contas` (
  `id_contas` INT NOT NULL,
  `valor_pago` FLOAT NULL,
  `credor` VARCHAR(45) NULL,
  `dt_pag_cred` DATE NULL,
  `rateio` TINYINT NULL,
  `separacao_custos` VARCHAR(45) NULL,
  `id_recebimentos` INT NULL,
  `base_contascol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_contas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_recebimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_recebimentos` (
  `id_recebimentos` INT NOT NULL,
  `valor_par` FLOAT NULL,
  `parcela_atual` INT NULL,
  `stat_pag_pj` VARCHAR(45) NULL,
  `dt_fat` DATE NULL,
  `dt_pag` DATE NULL,
  `obs_pag` VARCHAR(100) NULL,
  `id_unidade` INT NULL,
  `id_projetos` INT NULL,
  `base_unidade_id_unidade` INT NOT NULL,
  `base_contas_id_contas` INT NOT NULL,
  PRIMARY KEY (`id_recebimentos`),
  INDEX `fk_base_recebimentos_base_unidade1_idx` (`base_unidade_id_unidade` ASC) VISIBLE,
  INDEX `fk_base_recebimentos_base_contas1_idx` (`base_contas_id_contas` ASC) VISIBLE,
  CONSTRAINT `fk_base_recebimentos_base_unidade1`
    FOREIGN KEY (`base_unidade_id_unidade`)
    REFERENCES `mydb`.`base_unidade` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_recebimentos_base_contas1`
    FOREIGN KEY (`base_contas_id_contas`)
    REFERENCES `mydb`.`base_contas` (`id_contas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_modulo` (
  `id_modulo` INT NOT NULL,
  `modulo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_comb_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_comb_modulo` (
  `id_servico` INT NULL,
  `id_modulo` INT NULL,
  `id_projetos` INT NULL,
  `base_modulo_id_modulo` INT NOT NULL,
  `base_servicos_id_servicos` INT NOT NULL,
  INDEX `fk_base_comb_modulo_base_modulo1_idx` (`base_modulo_id_modulo` ASC) VISIBLE,
  INDEX `fk_base_comb_modulo_base_servicos1_idx` (`base_servicos_id_servicos` ASC) VISIBLE,
  CONSTRAINT `fk_base_comb_modulo_base_modulo1`
    FOREIGN KEY (`base_modulo_id_modulo`)
    REFERENCES `mydb`.`base_modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_comb_modulo_base_servicos1`
    FOREIGN KEY (`base_servicos_id_servicos`)
    REFERENCES `mydb`.`base_servicos` (`id_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_projetos` (
  `id_projetos` INT NOT NULL,
  `nome_pj` VARCHAR(45) NULL,
  `situacao` VARCHAR(45) NULL,
  `tag_status` VARCHAR(45) NULL,
  `estagio` VARCHAR(45) NULL,
  `num_de_parcelas` INT NULL,
  `obs_pj` VARCHAR(45) NULL,
  `f_pag` VARCHAR(45) NULL,
  `val_inovacao` FLOAT NULL,
  `valor` FLOAT NULL,
  `dt_resposta` DATE NULL,
  `dt_fim_pj` DATE NULL,
  `dt_ini_pj` DATE NULL,
  `dt_pedido` DATE NULL,
  `pinn` VARCHAR(45) NULL,
  `dt_deadline` DATE NULL,
  `dt_envio` DATE NULL,
  `motivo_de_atraso` VARCHAR(200) NULL,
  `tipo_da_eq` VARCHAR(45) NULL,
  `etp_atual_proj` VARCHAR(100) NULL,
  `falor_geral` VARCHAR(45) NULL,
  `id_servico` INT NULL,
  `id_empresa` INT NULL,
  `id_clientes` INT NULL,
  `id_comb_unid` INT NULL,
  `base_servicos_id_servicos` INT NOT NULL,
  `base_clientes_id_clientes` INT NOT NULL,
  `base_empresas_id_empresas` INT NOT NULL,
  `base_comb_unidade_id_comb_unidade` INT NOT NULL,
  `base_recebimentos_id_recebimentos` INT NOT NULL,
  `base_custos_id_custos` INT NOT NULL,
  INDEX `fk_base_projetos_base_servicos1_idx` (`base_servicos_id_servicos` ASC) VISIBLE,
  INDEX `fk_base_projetos_base_clientes1_idx` (`base_clientes_id_clientes` ASC) VISIBLE,
  INDEX `fk_base_projetos_base_empresas1_idx` (`base_empresas_id_empresas` ASC) VISIBLE,
  INDEX `fk_base_projetos_base_comb_unidade1_idx` (`base_comb_unidade_id_comb_unidade` ASC) VISIBLE,
  INDEX `fk_base_projetos_base_recebimentos1_idx` (`base_recebimentos_id_recebimentos` ASC) VISIBLE,
  INDEX `fk_base_projetos_base_custos1_idx` (`base_custos_id_custos` ASC) VISIBLE,
  PRIMARY KEY (`id_projetos`),
  CONSTRAINT `fk_base_projetos_base_servicos1`
    FOREIGN KEY (`base_servicos_id_servicos`)
    REFERENCES `mydb`.`base_servicos` (`id_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_projetos_base_clientes1`
    FOREIGN KEY (`base_clientes_id_clientes`)
    REFERENCES `mydb`.`base_clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_projetos_base_empresas1`
    FOREIGN KEY (`base_empresas_id_empresas`)
    REFERENCES `mydb`.`base_empresas` (`id_empresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_projetos_base_comb_unidade1`
    FOREIGN KEY (`base_comb_unidade_id_comb_unidade`)
    REFERENCES `mydb`.`base_comb_unidade` (`id_comb_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_projetos_base_recebimentos1`
    FOREIGN KEY (`base_recebimentos_id_recebimentos`)
    REFERENCES `mydb`.`base_recebimentos` (`id_recebimentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_projetos_base_custos1`
    FOREIGN KEY (`base_custos_id_custos`)
    REFERENCES `mydb`.`base_custos` (`id_custos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comb_modulo`
    FOREIGN KEY (`id_projetos`)
    REFERENCES `mydb`.`base_comb_modulo` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
